### ISSUE TITLE
Create a Query Builder to allow a user to add Cohort and Data queries to their requests

### ISSUE THREAD

**Issue by NigelPalmer** [MauroDataMapper/mdm-explorer#162]
When a user makes a request for data they need to have the ability to limit the data that is returned. They will do this by using two queries. The first will be a Cohort that identifies the types of patients that they require. The second is a Data query that will provide further refinement of data relating to the Cohort. The Query Builder needs to be a UI tool that allows a user to easily create queries. It should have an advanced mode that allows a user to free type a query if they want to do something a bit more complicated. These queries will be presented in a query language that has been defined by James Welch.
- [ ] Create proof of concept Query Builder and add it to the request page.
- [ ] Persist query in mauro database.
- [ ] Add Query Builder free text mode to allow queries to be typed in.
- [ ] Handle large datasets when populating combo boxes.
- [ ] Generate safe SQL to be run against data warehouse.
- [ ] Redesign the explorer UI to include the Query Builder in a sensible way.
