### ISSUE TITLE
Add Theming to Mdm Explorer

### ISSUE THREAD

**Issue by NigelPalmer** [MauroDataMapper/mdm-explorer#270]
# Description

The Mdm Explorer requires dynamic theming to be applied by administrators, without the need to rebuild the application. The administrator will be able to choose the colours to use, change the fonts, and upload logos. The management of the theme will be done in the Mdm UI, and the themes itself will be stored in the database in the backend. Therefore these changes will touch upon various different Mauro components, which will all need to come together to fulfil this requirement.

# Associated Tasks

## Colors and Fonts

- [x] #264 
- [x] MauroDataMapper-Plugins/mdm-plugin-explorer#18
- [x] MauroDataMapper-Plugins/mdm-plugin-explorer#19
- [x] #274 
- [x] MauroDataMapper/mdm-ui#760

## Images

- [x] MauroDataMapper/mdm-core#394
- [x] MauroDataMapper/mdm-resources#100
- [x] MauroDataMapper/mdm-ui#761
- [x] #276

## Other

- [x] MauroDataMapper-Plugins/mdm-plugin-explorer#23

**Comment by NigelPalmer** [comment]
All tasks are complete. Closing.
