### ISSUE TITLE
Complete Requests functionality (Epic)

### ISSUE THREAD

**Issue by NigelPalmer** [MauroDataMapper/mdm-explorer#351]
This issue is to group all the work that is related to the request page so that we can make sure it is merged at the same time.

# Allow researcher to create requests

- [x] maurodatamapper/sde-core#128
- [x] maurodatamapper/sde-resources#34
- [x] #347 

Note the changes implemented in the PRs for the above issues focus on these agreed requirements (slightly different to #347):

1. Allow a researcher to create a new request in "draft" status
2. Submit that request to "Awaiting approval" status
3. Allow a researcher to perform request actions for submitting a request approval

No other request status transitions are supported for a researcher yet.

Also, the list of requests a researcher sees is complete from a front-end perspective, but requires more backend work - see MauroDataMapper/sde-core#132.

# Additional changes

These changes focus on making sure other parts of the SDE are still functioning after altering the shared backend and component library.

- [x] maurodatamapper/sde-admin-ui#127
- [x] maurodatamapper/sde-resources#37

**Comment by NigelPalmer** [comment]
All issues in this epic have been merged.
