### ISSUE TITLE
Requests: Upload documents (Epic)

### ISSUE THREAD

**Issue by NigelPalmer** [MauroDataMapper/mdm-explorer#352]
An issue to keep track of all the issues related to the uploading of request documents.

- [x] maurodatamapper/sde-resources#25
- [x] maurodatamapper/sde-core#130

### Virus scanning
- [x] maurodatamapper/sde-core#149
- [x] maurodatamapper/sde-resources#71

**Comment by NigelPalmer** [comment]
All issues have been completed
