### ISSUE TITLE
SDE Request Creation - Complete Functionality

### ISSUE THREAD

**Issue by NigelPalmer** [MauroDataMapper/mdm-explorer#364]
# Description

Requests can now be created in the MDE but we are not quite at the point where we can send them to the SDE. The following issues will complete this functionality providing us with end to end workflow of requests.

- [ ] MauroDataMapper/sde-core#132
- [ ] MauroDataMapper/sde-resources#65
- [ ] MauroDataMapper/sde-resources#66

________________________________________________________________________
## Implement remaining statusChangeCommands for researchers

- [x] maurodatamapper/sde-core#159
- [x] maurodatamapper/sde-core#176
- [x] maurodatamapper/sde-core#177
- [x] maurodatamapper/sde-core#178
- [x] maurodatamapper/sde-core#179
- [x] maurodatamapper/sde-core#180

________________________________________________________________________
## Refactor use of ActionPermission
Remove actionPermission from requests-list.component and instead retrieve this information on a per request basis when loading the data for the dialog.

- [ ] maurodatamapper/sde-resources#92 
- [ ] maurodatamapper/sde-core#187

________________________________________________________________________
**Question: do we plan to add RETURN_TO_AUTHOR as an action for researcher-approvers?**

________________________________________________________________________
## Bug fixes

- [ ] maurodatamapper/sde-resources#99
- [ ] maurodatamapper/sde-resources#100
