### ISSUE TITLE
Rewrite request list getting

### ISSUE THREAD

**Issue by abwilson23** [MauroDataMapper/mdm-explorer#367]
The code that gets a list of requests needs to be improved to allow developers to have more confidence in any changes that are required in this area.

It has been suggested that the "criteria" approach is used to build the query. See this link: https://docs.jboss.org/hibernate/orm/6.3/userguide/html_single/Hibernate_User_Guide.html#criteria .

Other improvements are to have a single filter class that can hold many filter types. This will prevent the signature of the functions from having to be changes each time a new filter is added.

Another important aspect of this task is that the base data that filters can be applied to changes depending on what type of user is requesting the data. We need to make sure that if a user attempts to list all requests, only those that they are allowed to see are returned from the sde-core.

Complete when:

- [x] maurodatamapper/sde-core#132
- [x] maurodatamapper/sde-core#147
- [x] maurodatamapper/sde-core#148
- [x] maurodatamapper/sde-core#170

**Comment by NigelPalmer** [comment]
All associated tasks are now complete. This can be closed.
