### ISSUE TITLE
Make use of UserDetails consistent across mde, sde, and sde-resources

### ISSUE THREAD

**Issue by abwilson23** [MauroDataMapper/mdm-explorer#374]
This epic aims to make consistent the retrieval of the sde users details from the MDE and SDE respectively. 

The `ISdeSecurity` interface in the sde-resources defines a `getSignedInUser()` method which returns a `UserDetails` object. The MDE and SDE implement this interface in their respective sde security services so the sde-resources can consume the signed in users details from either application. However, currently the MDE is returning details related to the mdm backend instead of the sde backend. For example, the mdm userId instead of the sdeUserId.  In fact, there are two different definitions of `UserDetails`, one defined in the MDE and one in sde-resources. 

Complete When: 
- [x] `UserDetails` in sde-resources is renamed to `SdeUserDetails`
- [x] The renaming changes are propogated throughout the sde-admin-ui
- [x] The `SdeSecurity.getSignedInUser()` method in the MDE will return an `SdeUserDetails` object which is populated with the correct sdeUser information instead of the mdmUser information

**Related tickets**
- [x] #375
- [x] maurodatamapper/sde-admin-ui#174
- [x] maurodatamapper/sde-resources#101

**Comment by NigelPalmer** [comment]
All related tasks have been completed
