### ISSUE TITLE
Data Specification submissions (Epic)

### ISSUE THREAD

**Issue by NigelPalmer** [MauroDataMapper/mdm-explorer#383]
# Overview

This Epic is to collate all the tasks that are required to create Data requests and make sure that all relevant data is included in those requests.

### Ground work
- [x] #382
- [x] maurodatamapper/sde-core#191
- [x] #397 
- [x] maurodatamapper/sde-core#195

### Submission Service
- [x] #387 
- [x] #394 
- [x] #396
- [x] #402
- [x] #403 

### Further work
- [x] #386
- [ ] #395 
- [x] maurodatamapper/sde-core#199
- [x] maurodatamapper/sde-core#201

# Description
When a data specification is submitted the following steps need to be processed:

1. User is prompted to select a Project
2. A Data request is created. The title and content are prepopulated with the title and description from the data specification
3. A meql to sql file is generated
4. The meql to sql file is attached to the Data Request
5. A PDF representation of the Data Specification is generated
6. The PDF is attached to the request
7. The request is submitted.

This process is reliant on the mdm-core, sde-core and azure all behaving as they should. This means that this process could fail between any of the numbered points. If it does the data needs to be left in a state that allows the user to continue from the failed step if when they attempt to submit again. 

A service will be created which will process a list of steps. Each step will be defined as it's own step service object and will be an independent entity that can easily be plugged into the step list. These step entities will need to be able to run their content asynchronously and therefore the steps will need to be processed recursively since each step will be reliant on data from the previous step. If an error occurs then the submission process should be aborted.

After step 3 above has been completed a request will exist in draft from in the requests list. If a user opened that request and clicked submit then all of the steps above should be run instead of the standard request submit action.  It is also important to check that the user who created the request is the same user who created the data specification. This could go out of alignment in development due to moving the login around different types of SDE users. This will not be an issue in the live system because the login will never be associated with different users. But, it is important to handle this since this could cause confusion and pain when using the system as a developer which will ultimately cost us time.
