### ISSUE TITLE
Registration of Organisations, Departments and Users

### ISSUE THREAD

**Issue by NigelPalmer** [MauroDataMapper/mdm-explorer#421]
# Target
The MDE shall be a public-facing website that will present unregistered users with a landing page that explains the purpose of the MDE and has a link to a page that allows the user to register for full access to the MDE. Upon approval of their registration, users will be granted full access to MDE features.

During the user registration process, users will be able to register new organisations and departments. They will also be able to view limited information about all existing registered organisations and departments, allowing them to determine if the desired organisation or department is already registered.

SDE admins will have tools to manage and restrict user access as needed. 

To ensure a smooth user experience when logging in and out of the MDE and SDE, all login-related error messages will be presented in a user-friendly manner, and session timeouts will be properly aligned.

# Approach 
Work with OUH to design the necessary pages for user, organisation and department registrations, as well as user management. Work with OUH to determine the process for creating users in the linked OpenID provider and implement this feature.

Additionally, thoroughly test all login and logout workflows, ensuring that any errors are identified and presented to users in a friendly manner.

# Description

The MDE shall be a public facing website that will present unregistered users with a landing page that explains the purpose of the MDE and has a link to a page that allows the user to register for full access to the MDE. Once the registration has been approved the user will have full access. 

During the user registration process, users will be able to register new organisations and departments. They will be able to view limited information about all existing registered Organisations and Departments so that the user can identify if the organisation or department already exists.

SDE admins will be provided with tools to manage the access of users and restrict their access as necessary.
Ensure a smooth user experience when logging in and out of the MDE and SDE, including presenting all login-related error messages in a user friendly way and aligning timeouts.

# Additional
This diagram explains how this should work: [lifecycle - user account.pdf](https://github.com/user-attachments/files/16391829/lifecycle.-.user.account.pdf)

# Planning and Requirements

View these tasks to track planning and design notes:

- #445 

> Note: there are some older planning notes made, but these are now obsolete. I'll keep the links here for reference.
> 
> - #429 
> - #430 

# Tasks

## Requirements, Design and Planning

- [x] #445

## Organisation Administration

- [ ] MauroDataMapper/sde-core#230
- [ ] MauroDataMapper/sde-core#244
- [ ] MauroDataMapper/sde-resources#132
- [ ] MauroDataMapper/sde-admin-ui#189

### Backend

- [ ] MauroDataMapper/sde-core#235
- [ ] MauroDataMapper/sde-core#234
- [ ] MauroDataMapper/sde-core#246
- [ ] MauroDataMapper/sde-core#247
- [ ] MauroDataMapper/sde-core#233
- [ ] MauroDataMapper/sde-core#248
- [ ] MauroDataMapper/sde-core#249
- [ ] MauroDataMapper/sde-core#250
- [ ] MauroDataMapper/sde-core#251
- [ ] MauroDataMapper/sde-core#252
- [ ] MauroDataMapper/sde-core#253

### Frontend

- [ ] MauroDataMapper/sde-resources#127
- [ ] MauroDataMapper/sde-resources#133
- [ ] MauroDataMapper/sde-resources#134
- [ ] MauroDataMapper/sde-resources#135
- [ ] MauroDataMapper/sde-resources#136
- [ ] MauroDataMapper/mdm-explorer#442
- [ ] MauroDataMapper/mdm-explorer#449

## Other...

- [x] maurodatamapper/sde-core#208
- [x] maurodatamapper/sde-resources#119
- [ ] MauroDataMapper/mdm-explorer#450
- [ ] MauroDataMapper/sde-core#254
- [ ] MauroDataMapper/mdm-explorer#451
