### ISSUE TITLE
Elaboration of request forms to capture all data

### ISSUE THREAD

**Issue by NigelPalmer** [MauroDataMapper/mdm-explorer#422]
# Target
All request forms shall be updated so that they capture all the data that is required for each request type.

# Approach 
Enhance the existing request dialogs so that they capture all the data. 
This shall involve adding new components and making sure that all data is clear and easy to view and update.

Details about new requests form will be provided whenever ready (they won't come all together).

### Additional Information
- We will also need to create a Department entity. Organisations are to be made up of many departments.
  Registration requests; User, Organisation and Department; will be implemented in maurodatamapper/mdm-explorer#421

- Groundwork --> paused
  These tasks are currently paused as we cannot get all New forms together. These tasks could be a good enhancement to be done in the future - after all forms will be finalised) 
  - maurodatamapper/sde-core#207
  - maurodatamapper/sde-resources#118

# List of Requests/Tasks
_Please create pairs of sde-core and sde-resources tasks and add them to this epic as each request type is worked on._
NOTE: Order is given by the new request description availability

- **Project Enquiry Form**
This is a new request type which is intended to be used by researcher as a "feasibility request". Basically used to try to understand if their idea of project could be realised.
  - [x] maurodatamapper/sde-core#239
  - [x] maurodatamapper/sde-resources#137

- **New Project Request**
  - [x] maurodatamapper/sde-core#210

## Requests still WIP [new forms not delivered]
- A project change request
- An information request - this is typically a request for aggregate information, and will normally be supported by a data specification. (I suspect this is the same as a project feasibility request)
- a data request
- a resource request - workspace resources
- an import request
- an export request
- an archive request
- a help request - can be made by any user at any time

**Comment by giovannaOCC** [comment]
We didn't get all the properties for all requests during this project. Follow-up tasks has been created to Go-Live project to finalise all Request and complete the implementation
