### ISSUE TITLE
Create a registration page to request a user account for Mauro/SDE

### ISSUE THREAD

**Issue by pjmonks** [MauroDataMapper/mdm-explorer#442]
# Description

There needs to be a page in the Mauro Data Explorer, accessible to anyone (without sign-in), where someone can fill in a registration form and submit it to the SDE for processing.

**Todo:**
- [x] Create the registration form page and provide a way to acces it. 
- [x] Create the form and allow for form submission / alteration depending on inputs. 
- [ ] Wire up the submission of the form to an endpoint. (Currently, there is no api endpoint for retrieving the payload. Or sde-resources endpoint library entries for such an endpoint.)

# Depends on

- MauroDataMapper/sde-core#233
- MauroDataMapper/sde-resources#136

# Registration Form

The form fields to present are defined in:

- #445 

For selecting an existing Organisation and/or Department, the new endpoints created in the SDE for fetching them (anonymously) will need to be used, so that the Department list is dynamic in relation to a selected Organisation. See MauroDataMapper/sde-core#233.

# UI/UX

The style/layout of the registration form should match the Mauro Data Explorer - a dialog is not required like the typical request dialogs used by the SDE.

Use sensible UX ideas to complete the page e.g. make it clear to the user, provide feedback on errors/validation, etc.

# Submission

This task just needs to focus on the registration form itself. Handling submission and requests to create will be handled in:

- #449.
