### ISSUE TITLE
Create organisation page in user portal

### ISSUE THREAD

**Issue by abwilson23** [MauroDataMapper/mdm-explorer#486]
# Description

Add back the organisation page in the User Portal. It will be a combination of the Departments page a new organisation page. Specifically, it will be the Departments page exactly as it now is with an additional mat-card across the top which includes relevant information about the users organisation and a list of organisation members. 

This work will provide an organisation members list to use which is the main list being added to the organisation card: https://github.com/MauroDataMapper/sde-resources/issues/203

**Todo:** 
- [x] Add new mat-card to the top of the existing departments page. 
- [x] Display the users organisation information along with a list of the organisation members in the card. 

**Note:**
There is currently an entire organisation page which is the org information, a dummy member list, and a requests list implemented in the PR linked to this issue. The spec has changed since this implementation and we've decided on a much simpler approach outlined above. I recommend you: 
- [ ] Remove the requests list component from the organisations page html. 
- [x] Copy the <mat-card> containing the organisation details and member list (swap over to using this one when complete: https://github.com/MauroDataMapper/sde-resources/issues/203) over to the top of the departments page. 
- [ ] Reformat the card to look a little nicer. 

# Additional context

This work also includes a small follow up task:
- [ ] Remove NewOrganisationRequest from the list of requests a researcher can create. This request can only be created as a side effect of the registration process.
